version: "3.7"

services:
  sample:
    container_name: bdafrontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 4001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
